// ERRORS
// export const GET_ERRORS = "GET_ERRORS";
// export const CLEAR_ERRORS = "CLEAR_ERRORS";
//USER
// export const SET_CURRENT_USER = "SET_CURRENT_USER";
// export const SET_SIGN_STEP = "SET_SIGN_STEP";
// export const SET_SIGN_PHONE = "SET_SIGN_PHONE";
// export const SET_SIGN_UUID = "SET_SIGN_UUID";
// export const GET_SIGN_ERRORS = "GET_SIGN_ERRORS";
// export const CHANGE_SHOW_SIGN = "CHANGE_SHOW_SIGN";
// export const CLEAR_CURRENT_COMPANY = "CLEAR_CURRENT_COMPANY";
//PROFILE
// export const CHANGE_PROFILE = "CHANGE_PROFILE";
// export const GET_PROFILE = "GET_PROFILE";
// export const SHOW_PROFILE_MODAL = "SHOW_PROFILE_MODAL";
//COMPANY
// export const COMPANY_LOADING = "COMPANY_LOADING";
// export const COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND";
// export const CLEAR_CURRENT_COMPANY = "CLEAR_CURRENT_COMPANY";
// export const GET_COMPANIES = "GET_COMPANIES";
